<a href="https://colab.research.google.com/github/MartaSolarz/Data_science_theory/blob/main/01_numpy/Numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
dir(np) # wyświetla jakie mamy funkcje

In [ ]:
help(np.array)

# 1. Podstawy - array

- array 1D
- array 2D
- array 3D

Array 1D

In [ ]:
# definiowanie tablicy jednowymiarowej
x = np.array([1,3])
x

array([1, 3])

In [ ]:
print(x)
print(type(x))

[1 3]
<class 'numpy.ndarray'>


In [ ]:
# wymiar tablicy
x.ndim

In [ ]:
# kształt tablicy
x.shape

In [ ]:
# liczba elementów w tablicy
x.size

In [ ]:
# typ danych przechowywanych przez tablicę
x.dtype

Array 2D

In [ ]:
x = np.array([[1,2],[3,4]])

In [ ]:
print(x)

[[1 2]
 [3 4]]


In [ ]:
x.shape

(2, 2)

Array 3D

In [ ]:
x = np.array(
    [[[1,2,3], 
      [2,4,6]],
     
     [[1,4,7],
      [3,6,9]],
     
     [[1,2,3],
      [0,4,6]]]
)

In [ ]:
print(x)

[[[1 2 3]
  [2 4 6]]

 [[1 4 7]
  [3 6 9]]

 [[1 2 3]
  [0 4 6]]]


In [ ]:
x.shape  # (liczba zbiorów "wysokość", wiersze, kolumny)

(3, 2, 3)

In [ ]:
np.array([[[1,2,3], [2,3,4]]]).shape

(1, 2, 3)

# 2. Typy danych

- sprawdzanie typu (np.dtype)
- narzucanie typu (dtype='')

TYPY:
- int
- float
- complex (liczby złożone)
- bool

In [ ]:
# sprawdzanie typu danych w tablicy

x.dtype

In [ ]:
# można przy tworzeniu tablicy narzucić jaki to ma być typ danych

x = np.array([[1,2,4,5], [3,5,6,7]], dtype='complex')
x

array([[1.+0.j, 2.+0.j, 4.+0.j, 5.+0.j],
       [3.+0.j, 5.+0.j, 6.+0.j, 7.+0.j]])

In [ ]:
# możemy też określać liczbę bitów typów np:
x = np.array([25,67,88], dtype=np.int8)
x.dtype

dtype('int8')

In [ ]:
# do obrazów stosujemy: (Computer Version - na koniec kursu)
x = np.array([25,67,88], dtype=np.uint8)
x.dtype

dtype('uint8')

# 3. Tworzenie tablic

- zeros
- ones
- full
- arange
- linspace

Modyfikacja kształtu:
- reshape

In [ ]:
# tablia z samych zer, można podać typ tych danych
np.zeros(shape=(2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# wypełnia tablice dowolnymi wartościami - przydatne np. do tworzenia masek
np.full(shape=(3,3), fill_value=5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
# tablica - liczby z zakresu (analogiczne do range)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# określamy krok między początkiem i końcem przedziału
np.arange(start=5,stop=100,step=15)

array([ 5, 20, 35, 50, 65, 80, 95])

In [ ]:
# możemy też malejąco:
np.arange(start=100,stop=5,step=-15)

array([100,  85,  70,  55,  40,  25,  10])

In [ ]:
# podobne do arange - wskazujemy ile wartości równo rozłożonych chcemy wygenerować z podanego zbioru
np.linspace(start=10, stop=100, num=12)

array([ 10.        ,  18.18181818,  26.36363636,  34.54545455,
        42.72727273,  50.90909091,  59.09090909,  67.27272727,
        75.45454545,  83.63636364,  91.81818182, 100.        ])

In [ ]:
# zmiana kształtu

tablica = np.arange(15)

In [ ]:
tablica.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
# lub numpy automatycznie wykryje:
tablica.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# 4. Podstawowe operacje na tablicach

- dodawanie: A+B lub np.add(A, B)
- odejmowanie: A-B lub np.subtract(A, B)
- mnożenie: A*B lub np.multiply(A, B)
- dzielenie: A/B lub np.divide(A, B)
- mnożenie macierzowe: np.dot(X, Y) lub X.dot(Y) lub X@Y

In [2]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])

In [3]:
# dodawanie element po elemencie
A + B

array([6, 0, 7, 4])

In [4]:
# odejmowanie element po elemencie
A - B

array([0, 2, 1, 0])

In [5]:
# mnożenie
A * B

array([ 9, -1, 12,  4])

In [6]:
# dzielenie *nie może w tablicy być zero!*
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [7]:
# dodatnie 3 do każdego elementu
A + 3

array([6, 4, 7, 5])

In [8]:
# bardziej złożone operacje
A + 3*B

array([12, -2, 13,  8])

In [9]:
# alternatywnie mamy też metody:
np.add(A, B) # dodatnie tablic
np.subtract(A, B) # odejmowanie tablic
np.multiply(A, B) # mnożenie tablic
np.divide(A, B)  # dzielenie tablic

array([ 1.        , -1.        ,  1.33333333,  1.        ])

Mnożenie macierzowe 
- np.dot(X, Y)
- X.dot(Y)
- X @ Y

In [10]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])

In [11]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [12]:
# drugi sposób
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [14]:
# UWAGA - mnożenie macierzy nie jest przemienne!
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [15]:
# trzeci sposób
X @ Y

array([[  3,   6],
       [-12,   0]])

# 5. Generowanie liczb pseudolowych

### Wbudowany moduł random:
- np.random.randn() - rozkład N(0,1)
- np.random.rand() - rozkład U[0, 1)
- np.random.randint() - nieujemna całkowita z przedziału
- np.random.choice([list]) - element z podanej listy
- np.random.shuffle() - losowe przetasowanie


In [16]:
# ustawienie konkretnego ziarna losowego - zawsze ten sam wynik
np.random.seed(0)

In [17]:
# generowanie losowej liczby z rozkładu normalnego standardowego N(0,1)
np.random.randn()

1.764052345967664

In [18]:
# możemy podać ile chcemy tych liczb
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [19]:
np.random.randn(10, 4)  # liczba wierszy i kolumn

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [20]:
# generowanie liczby z rozkładu jednostajnego na przedziale Unit[0, 1)
np.random.rand() 

0.1965823616800535

In [21]:
np.random.rand(10, 4)

array([[0.36872517, 0.82099323, 0.09710128, 0.83794491],
       [0.09609841, 0.97645947, 0.4686512 , 0.97676109],
       [0.60484552, 0.73926358, 0.03918779, 0.28280696],
       [0.12019656, 0.2961402 , 0.11872772, 0.31798318],
       [0.41426299, 0.0641475 , 0.69247212, 0.56660145],
       [0.26538949, 0.52324805, 0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895, 0.66741038, 0.13179786],
       [0.7163272 , 0.28940609, 0.18319136, 0.58651293],
       [0.02010755, 0.82894003, 0.00469548, 0.67781654],
       [0.27000797, 0.73519402, 0.96218855, 0.24875314]])

In [24]:
# generowanie losowej liczby całkowitej nieujemnej
np.random.randint(10)  # liczba z przedziału [0,10)

3

In [26]:
# możemy też wybrać przedział i liczbę liczb
np.random.randint(low=11, high=101, size=5)

array([37, 77, 63, 78, 72])

In [27]:
# losowy wybór elementu z podanej listy
np.random.choice([1,5,8,9])

8

In [28]:
# mogą to być też inne typy zmiennych
np.random.choice(['java', 'python', 'sql'])

'java'

In [30]:
# losowe przetasowanie tablicy
data = np.arange(10)
np.random.shuffle(data) # modyfikuje dane wyjściowe!
data

array([9, 3, 2, 7, 4, 0, 1, 6, 5, 8])

# 6. Podstawowe funkcje

- np.exp()
- np.sqrt()
- np.all()
- np.any()
- np.argmax()
- np.argmin()
- np.argsort()
- np.max()
- np.min()
- np.sum()
- np.mean()
- np.median()
- np.std() 

In [38]:
np.exp(1) # pow(e,1)

2.718281828459045

In [40]:
np.sqrt(4) # pierwiastek kwadratowy

2.0

In [41]:
np.all([-1, 9]) # czy wszystkie liczby zwracają True -> 0 zwraca False

True

In [43]:
np.any([0, 3]) # czy istnieje jakaś liczba zwracająca True, przydatne do sprawdzania w danych czy są jakieś niezerowe wartości

True

In [46]:
bool(0) # zwraca wartość logiczną liczby - False zwraca tylko 0

False

In [47]:
# zwracanie indeksu gdzie wartość w tablicy jest:
A = np.random.rand(5)
A

array([0.95608363, 0.6439902 , 0.42385505, 0.60639321, 0.0191932 ])

In [50]:
np.argmax(A) # największa
np.argmin(A) # najmniejsza

4

In [52]:
# sortowanie wartości podając index: od najmniejszej do największej
np.argsort(A)

array([4, 2, 3, 1, 0])

In [58]:
# wartości statystyczne:
np.max(A)
np.min(A)
np.mean(A)
np.median(A)
np.std(A) # odchylenie standardowe
np.sum(A)

2.6495152949482987

# 7. Indeksowanie i wycinanie

- wycinanie - jak w listach w pythonie, w przypadku wielowymiarowych A[,]
- modyfikowanie tablicy też jest mozliwe w ten sposób A[1,3] = 10

In [60]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
# wycinanie: - jak listy w pythonie
A[1:6]

array([1, 2, 3, 4, 5])

In [62]:
A[:2]

array([0, 1])

In [63]:
A[[0,2]]

array([0, 2])

In [68]:
A[-2:]

array([8, 9])

In [70]:
# Tablice o wyższych wymiarach
A = A.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [71]:
A[0] # wiersz

array([0, 1, 2, 3, 4])

In [73]:
A[:,4] # kolumna

array([4, 9])

In [75]:
A[1,4] # konkretny element

9

In [79]:
A[0:, 2:4] # fragment

array([[2, 3],
       [7, 8]])

In [80]:
# możemy też modyfikować tablicę w ten sposób
A[1,1] = 10
A

array([[ 0,  1,  2,  3,  4],
       [ 5, 10,  7,  8,  9]])



# 8. Iterowanie po tablicach

- pętla for (po wierszach lub po "wypłaszczonej tablicy" A.flat)
- enumerate(A) - kontrola liczby iteracji

In [82]:
# pętla for:
for row in A:
  print(row[:3])

[0 1 2]
[ 5 10  7]


In [84]:
# wypłaszczenie tablicy - iterowanie po każdym elemencie:
for item in A.flat:
  print(item)

0
1
2
3
4
5
10
7
8
9


In [87]:
# kontrolowanie liczby iteracji
for iteracja, item in enumerate(A):
  print('Iteracja nr:', iteracja, '| Wartość:', item)

Iteracja nr: 0 | Wartość: [0 1 2 3 4]
Iteracja nr: 1 | Wartość: [ 5 10  7  8  9]


# 9. Zmiana rozmiaru tablicy

- A.reshape()
- A.ravel() - wypłaszczenie
- A.T - transpozycja

In [95]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5, 10,  7,  8,  9]])

In [88]:
A.shape # sprawdzanie kształtu

(2, 5)

In [89]:
A.reshape(5, 2) # zmiana kształtu

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [10,  7],
       [ 8,  9]])

In [91]:
A.ravel() # wypłaszczenie danych

array([ 0,  1,  2,  3,  4,  5, 10,  7,  8,  9])

In [94]:
A.T # transponowanie

array([[ 0,  5],
       [ 1, 10],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9]])

# 10. Maski logiczne

- jeden warunek <, > itd
- więcej warunków: np.bitwise_and(), np.bitwise_or()

In [97]:
A = np.arange(-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [99]:
# chcemy się dowiedzieć gdzie są wartości ujemne:
A<0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [100]:
A[A<0]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5])

In [104]:
# więcej warunków
A[np.bitwise_and(A>-5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [105]:
A[np.bitwise_or(A>5, A<-5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])