<a href="https://colab.research.google.com/github/MartaSolarz/Data_science_theory/blob/main/Exercises/Numpy/071_080_wielomiany_datetime.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 71](#1)
* [Ćwiczenie 72](#2)
* [Ćwiczenie 73](#3)
* [Ćwiczenie 74](#4)
* [Ćwiczenie 75](#5)
* [Ćwiczenie 76](#6)
* [Ćwiczenie 77](#7)
* [Ćwiczenie 78](#8)
* [Ćwiczenie 79](#9)
* [Ćwiczenie 80](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.random.seed(42)
np.__version__

'1.21.6'

### <a name='1'></a> Ćwiczenie 71
Podana jest poniższa tablica $A$:

```
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
```
Od drugiego wiersza tablicy $A$ przestaw losowo wiersze w tablicy.

__Wskazówka:__ Użyj funkcji _np.random.shuffle()_.


In [4]:
# tutaj wpisz rozwiązanie

A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])

np.random.shuffle(A[1:])
A

array([['id', 'price'],
       ['002', '4.99'],
       ['001', '14.99'],
       ['004', '2.49'],
       ['005', '1.49'],
       ['003', '7.99']], dtype='<U32')

### <a name='2'></a> Ćwiczenie 72
Podana jest poniższa tablica $A$:

```
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
```
Zwróć tablicę indeksów, które posortują tablicę $A$ rosnąco.

__Oczekiwny wynik:__


```
array([5, 2, 1, 0, 4, 3])
```
__Wskazówka:__ Użyj funkcji _np.argsort()_.



In [5]:
# tutaj wpisz rozwiązanie

A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])

np.argsort(A)

array([5, 2, 1, 0, 4, 3])

### <a name='3'></a> Ćwiczenie 73
Podana jest poniższa tablica $A$:

```
A = np.random.randn(10, 8)
```

Zaokrąglij wartości tej tablicy do trzeciego miejsca po przecinku.

__Wskazówka:__ Użyj funkcji _np.round()_.

In [6]:
# tutaj wpisz rozwiązanie

A = np.random.randn(10, 8)

np.round(A, decimals=3)

array([[ 0.279,  1.011, -0.581, -0.525, -0.571, -0.924, -2.613,  0.95 ],
       [ 0.816, -1.524, -0.428, -0.742, -0.703, -2.14 , -0.629,  0.598],
       [ 2.559,  0.394,  0.122, -0.515, -0.6  ,  0.947,  0.291, -0.636],
       [-1.022, -0.162, -0.534, -0.006, -0.229,  0.389, -1.265,  1.092],
       [ 2.778,  1.194,  0.219,  0.882, -1.009, -1.583,  0.774, -0.538],
       [-1.347, -0.881, -1.131,  0.134,  0.582,  0.888,  0.894,  0.755],
       [-0.207, -0.623, -1.508,  1.1  , -0.178, -0.41 ,  1.18 , -0.898],
       [ 0.835,  0.297, -1.038, -0.076,  0.973,  0.796,  1.495,  0.338],
       [ 3.372, -0.92 , -0.399, -0.061, -1.419,  1.042,  0.904,  0.019],
       [-0.534, -1.495, -0.789,  0.744, -0.212, -0.427,  0.501,  1.158]])

### <a name='4'></a> Ćwiczenie 74
Wyznacz pierwiastki wielomianu:
* $W(x) = 4x^2 + 5x + 1$


__Wskazówka:__ Użyj funkcji _np.roots()_ oraz _np.polyval()_.

In [9]:
# tutaj wpisz rozwiązanie

np.roots([4,5,1])

array([-1.  , -0.25])

Dokonaj sprawdzenia.

In [13]:
# tutaj wpisz rozwiązanie

np.polyval([4,5,1], [-1,-0.25])

array([0., 0.])

### <a name='5'></a> Ćwiczenie 75
Wyznacz pierwiastki wielomianów:
* $Q(x) = 2x^3 + 4x^2 -5x + 1$
* $R(x) = 2x^3 -5x + 1$

__Wskazówka:__ Użyj funkcji _np.roots()_.

In [16]:
# tutaj wpisz rozwiązanie

q = np.array([2,4,-5,1])
r = np.array([2,0,-5,1])

print(np.roots(q))
print(np.roots(r))

[-2.91610583  0.65388685  0.26221898]
[-1.67298165  1.46961743  0.20336421]


### <a name='6'></a> Ćwiczenie 76
Podane są wielomiany:

* $W(x) = 4x^2 + 5x + 1$
* $Q(x) = 2x^3 + 4x^2 -5x + 1$


In [17]:
W = np.array([4, 5, 1])
Q = np.array([2, 4, -5, 1])

Wykonaj działania:
* $W(x) + Q(x)$

In [20]:
# tutaj wpisz rozwiązanie

np.polyadd(W, Q)

array([2, 8, 0, 2])

* $W(x) - Q(x)$


In [21]:
# tutaj wpisz rozwiązanie

np.polysub(W, Q)

array([-2,  0, 10,  0])

* $W(x) * Q(x)$


In [22]:
# tutaj wpisz rozwiązanie

np.polymul(W, Q)

array([  8,  26,   2, -17,   0,   1])

* $W(x) + 2Q(x)$

In [23]:
# tutaj wpisz rozwiązanie

np.polyadd(W, 2*Q)

array([ 4, 12, -5,  3])

### <a name='7'></a> Ćwiczenie 77
Podana jest poniższa tablica:

```
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
```

Użyj funkcji znaku (_sign function_) dla tablicy $A$. Dla przypomnienia funkcja działa nastpująco: dla wartości ujemnych zwraca -1, dla zera wartość zero, dla wartości dodatnich 1.

__Oczekiwany wynik:__


```
array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])
```
__Wskazówka:__ Użyj funkcji _np.sign()_.


In [24]:
# tutaj wpisz rozwiązanie

A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])

np.sign(A)

array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])

### <a name='8'></a> Ćwiczenie 78
Wykorzystując funkcję _np.arange()_ wygeneruj poniższą tablicę:


```
array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')
```



In [29]:
# tutaj wpisz rozwiązanie

np.arange(start='2021-01-01', stop='2021-02-01', dtype=np.datetime64)

array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')


### <a name='9'></a> Ćwiczenie 79

Wykorzystując funkcję _np.arange()_ wygeneruj poniższą tablicę:



```
array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')
```



In [32]:
# tutaj wpisz rozwiązanie

np.arange(start='2021-01', stop='2022-01', dtype=np.datetime64).reshape(4,-1)

array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')

### <a name='10'></a> Ćwiczenie 80

Wykorzystując funkcję _np.datetime64()_ wygeneruj dzisiejszą datę (datę w chwili robienia ćwiczenia).

In [36]:
# tutaj wpisz rozwiązanie

np.datetime64('today')

numpy.datetime64('2022-08-22')